#!/usr/bin/python
import string
import sys

def pretty_print(obj):
	#tuple or list 
	if isinstance(obj, tuple) or isinstance(obj, list):
		for x in obj:
			print x
	# Dict
	elif isinstance(obj, dict):
		for k, v in sorted(obj.items()):
			histogram = 'x'* v
			print u'{0}: {1}'.format(k, histogram)


	#anything else
	else:
		print obj

def counter(str):
	str= str.strip()
	str = str.strip(string.punctuation)
	list1=list(str)
	countDict= {}
	for l in list1:
		if l.isalpha():
			if l in countDict:
				countDict[l] +=1
			else:
				countDict[l]= 1

	pretty_print(countDict)

def main():
	first = "ARXTNUARDJHERHZMQECTDCLFMHKTHUARETCTEFTDIDREFTDCLAPTCJDRLDSNDHRQDREXNC HANVPAKNJTAOOACZAQQTRKACTFMHKTHRAEETERTDCKLRDUUHRZVNEETRKLQMTCTXDJTDQD UUHRZDVAOVAJTARTZTRQKLCDUUHRZCDUUHRZDQJLXMDJYTCEAACQHVVAJTPHVHQACHJNQQ TCTEQDUUHRZDQJLXMDJYTCEAACARKLQMHVDRERAQMHRZJACTDMEHVQHRXQKLHCTJTJYTCH QFDVHRQMTYKTDIETXTJYTCDRETDXMVTUDCDQTELHRZTJYTCFCANZMQHQVZMAVQNUARQMTO KAACTDZTCKLHFHVMTEQMTJACCAFPDHRKLHMDEVANZMQQAYACCAFOCAJJLYAAIVVNCXTDVT AOVACCAFVACCAFOACQMTKAVQKTRACTOACQMTCDCTDRECDEHDRQJDHETRFMAJQMTDRZTKVR DJTEKTRACTRDJTKTVVMTCTOACTPTCJACT"

	second="PCSIWTHXAZTCHPSJCRTGIPXCGJHIAXCVDUTPRWEJGEATRJGIPXCIWGXAATSBTUXAATSBTL XIWUPCIPHIXRITGGDGHCTKTGUTAIQTUDGTHDIWPICDLIDHIXAAIWTQTPIXCVDUBNWTPGIX HIDDSGTETPIXCVIXHHDBTKXHXIDGTCIGTPIXCVTCIGPCRTPIBNRWPBQTGSDDGHDBTAPITK XHXIDGTCIGTPIXCVTCIGPCRTPIBNRWPBQTGSDDGIWXHXIXHPCSCDIWXCVBDGTEGTHTCIAN BNHDJAVGTLHIGDCVTGWTHXIPIXCVIWTCCDADCVTGHXGHPXSXDGBPSPBIGJANNDJGUDGVXK TCTHHXXBEADGTQJIIWTUPRIXHXLPHCPEEXCVPCSHDVTCIANNDJRPBTGPEEXCVPCSHDUPXC IANNDJRPBTIPEEXCVIPEEXCVPIBNRWPBQTGSDDGIWPIXHRPGRTLPHHJGTXWTPGSNDJWTGT XDETCTSLXSTIWTSDDGSPGZCTHHIWTGTPCSCDIWXCVBDGT "

	third = "ULXYAOABKKSLRNMTGVJGAMXVGNFZRYSEYPIEDDWUKPIBEYYCLAEITDRTZLXKHZIOTJOZNO SGALXVMKIFMHRUTCIABNLKSKPHMVRZAIWUHYICEVZRGVFCAXOCEBQVANEGHRIEOAXUTAPZ EOLLLVYCHVXULWSBEIPRTCIDYGSAXSMEENWHGIVFKZRDNPXKHZFHLAESOQIZRKSFROEXXA LPBZEXYYSDOPXZROIRROEAWAEBEOLLYVVDFMSZHMJDYYSBKXYFTCXUXYEMEIRROLVDOMIN GKXYEMEIXURVVZVSEPXKIIKFMPPCINWVMAMEGNXVESMJSDXGBUKFNOLRIHPCIYFHLASWPV PYTZNLSOEOHCIDYXLNFIIIDJSETUHYINILXZLRVZEYEALVSZIZBUKFFVHRFVRJTCEGBZHI EVQVGNEEDOLREHQGLDKUMVIIHDQFMYIRMDRTMOVFWNLVLZLRDJABGALVFGSBKHRUMTWBNS JIOHSHMALRTNLNWVAKHVXYBLWWLJEGBUKFNOLRYSSFRNLNESFVLDJGXKRVVZVZHYI  " 

	if sys.argv[1] == '1':
		counter(first)
		exit(1)
	if sys.argv[1] == '2':
		counter(second)
		exit(1)
	if sys.argv[1] == '3':
		counter(third)
		exit(1)

	else:
		inputtext = raw_input("Paste string here:")
		counter(inputtext)
	
if __name__=="__main__":
	main()
